version: '3'
services:
  database:
    container_name: database
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CONTAINER: database
    build:
      context: .
      dockerfile: Dockerfile
      target: database
    ports:
      - 5432:5432
  api:
    container_name: api
    depends_on:
      - database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CONTAINER: api
    build:
      context: .
      dockerfile: Dockerfile
      target: api_server
    ports:
      - 80:8000
  scraper:
    container_name: scraper
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CONTAINER: scraper
    build:
      context: .
      dockerfile: Dockerfile
      target: scraper