version: '3.4'
services:
  news_scraper:
    container_name: news_scraper
    env_file:
      - ./scrapers/.env
    build:
      context: .
      dockerfile: Dockerfile
      target: scraper
    volumes:
      - ./scrapers:/scrapers
    command: ["bash", "-c", "npm run scrape:news"]
  weather_scraper:
    container_name: weather_scraper
    env_file:
      - ./scrapers/.env
    build:
      context: .
      dockerfile: Dockerfile
      target: scraper
    volumes:
      - ./scrapers:/scrapers
    command: ["bash", "-c", "npm run scrape:weather"]