import { useState } from "react"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { StickyHeader } from "../components/StickyHeader"
import { UserPanel } from "../components/UserPanel"
import { ContentZone } from "../components/ContentZone"


export default function Home() {
  return (
    <div className="md:container md:mx-auto">
      <Head>
        <title>myChattanooga</title>
        <meta name="description" content="Generated by create next app" key="siteDescription"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex w-screen h-24">
        <StickyHeader />
      </header>

      <main className="flex w-screen">
        {/* UserPanel needs to persist overall, but will need to show different user options depending on the page being shown */}
        <UserPanel />
        {/* Content Zone will contain components for one of the available pages */}
        <ContentZone/>  
              
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
