import { StickyHeader } from "./StickyHeader"
import { ContentZone } from "./ContentZone"
import Head from 'next/head'
import Image from 'next/image'
import { useState, createContext, useRef, useEffect } from "react"
import { MobileNav } from "./MobileNav"
import Script from "next/script"
import { MobileUserPanel } from "./MobileUserPanel"
import { faAngleUp } from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"

const MyChattanoogaContext = createContext();

export const MyChattanoogaProvider = ({ children }) => {

    const [menuExpanded, setMenuExpanded] = useState(false)
    const [panelExpanded, setPanelExpanded] = useState(false)
    const [isDark, setDark] = useState(false)
    const [weatherData, setWeatherData] = useState(null)
    const [defaultWeatherLocation, setDefaultWeatherLocation] = useState(null)

    function toggleMobileNav() {
        setMenuExpanded(menuExpanded => !menuExpanded)
    }
    function toggleMobileUserPanel() {
        setPanelExpanded(panelExpanded => !panelExpanded)
    }
    function toggleDarkMode() {
        setDark(isDark => !isDark);
        document.body.classList.contains('dark') 
            ? document.body.classList.remove("dark") 
            : document.body.classList.add("dark");
    }

    const value = {
        isExpanded: {menuExpanded},
        toggleMobileNav: {toggleMobileNav},
        panelExpanded: {panelExpanded},
        toggleMobileUserPanel: {toggleMobileUserPanel},
        toggleDarkMode: {toggleDarkMode}
    }

    const childrenComponentClassString = menuExpanded === true 
        ? "overscroll-contain scroll-smooth p-6 lg:px-8 lg:pt-8 bg-[#FFF] dark:bg-[#222] transition duration-[350ms] blur-sm ease-out"
        : "overscroll-contain scroll-smooth p-6 lg:px-8 lg:pt-8 bg-[#FFF] dark:bg-[#222]"

    return (
        <MyChattanoogaContext.Provider value={value}>
            <div className="flex flex-col h-screen overscroll-contain">
                <Head>
                        <title>myChattanooga</title>
                        <meta name="description" content="Generated by create next app" key="siteDescription"/>
                        <link rel="icon" href="/favicon.ico" /> 
                        <Script src="https://kit.fontawesome.com/27b6c4e65c.js" />
                </Head>

                <header className="relative w-screen shadow-sm bg-[#FFF] dark:bg-[#222]">
                    <StickyHeader isDark={isDark} />
                </header>

                <main className="w-screen h-screen align-center relative overflow-y-scroll" >
                    <div className="sm:hidden fixed w-full h-fit object-center -left-full z-50 flex mx-auto">
                        <MobileNav isDark={isDark} menuExpanded={menuExpanded} />
                    </div>
                    <div className="sm:hidden fixed w-full h-fit object-center -right-full bottom-0 z-50 mx-auto">
                        <MobileUserPanel isDark={isDark} panelExpanded={panelExpanded} toggleDarkMode={toggleDarkMode} />
                    </div>
                    <div className={childrenComponentClassString}>
                        {children}
                    </div>
                </main>

                {/* <footer className="flex items-center w-screen">
                    
                    <div className="flex-auto">
                        Hi
                    </div>
                        
                </footer> */}
            </div>
        </MyChattanoogaContext.Provider>
    )
}

export default MyChattanoogaContext
