export const REGION_KEYWORDS = [
  'chattanooga',
  'chatt state',
  ' chatt ',
  ' utc ',
  'east brainerd',
  'middle valley',
  'harrison',
  'apison',
  'monteagle',
  'hamilton county',
  'hamilton co',
  'signal mountain',
  'lookout mountain',
  'ridgeside',
  'soddy daisy',
  'soddy-daisy',
  'collegedale',
  'ridgeside',
  'hixson',
  'east ridge',
  'brainerd',
  'red bank',
  'red-bank',
  'ooltewah',
  'tva',
  'epb',
  'erlanger',
  'city council',
  'tennessee american water',
  'tennessee valley authority',
  'jasper',
  'avondale',
  'best and worst restaurant inspection',
  'st. elmo',
  'cpd',
  'north shore',
  "today's weather",
  'lee university',
  'cleveland',
  'suck creek',
  'collegedale',
];

export const KEYWORDS_TO_AVOID = [
  'georgia',
  'alabama',
  'north carolina',
  'jerry summers',
  'life with ferris',
  'fort oglethorpe',
  'dalton',
  'rossville',
  'ringgold',
  'catoosa',
  'biden',
  'kamala',
  'ohio',
  'white house',
  'get emailed headlines from chattanoogan.com',
  'tech byte',
];
