name: Prisma Migrate Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"

      - name: Install dependencies
        working-directory: scrapers
        run: npm install

      - name: Prisma Migrate Deploy
        working-directory: scrapers
        run: npx prisma migrate deploy
