name: Run myChattanooga Hub tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      working-directory: hub
      run: npm install && npx playwright install-deps

    - name: Install Playwright Browsers
      working-directory: hub
      run: npx playwright install

    - name: Run Unit Tests
      working-directory: hub
      run: npm run test

    - name: Run E2E Tests
      working-directory: hub
      run: npm run test:e2e

    
